services:
  hm10:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: hm10
    volumes:
      - ./input.txt:/app/input.txt
      - ./output.txt:/app/output.txt
    ports:
      - "8080:8080"
    command: ["java", "-jar", "hm10.jar"]