services:
  postgres:
    image: postgres:latest
    env_file: local.env
    ports:
      - "5432:5432"

  app:
    image: app
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    env_file: local.env

volumes:
    postgres-data:  # Определяем именованный том для postgres