
CREATE TABLE IF NOT EXISTS offices (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    is_deleted BOOLEAN DEFAULT FALSE NOT NULL
);

CREATE TABLE IF NOT EXISTS doctors (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(30) NOT NULL,
    phone VARCHAR(20) NOT NULL,
    work_hours_from TIMESTAMP NOT NULL,
    work_hours_for TIMESTAMP NOT NULL,
    office_id BIGINT NOT NULL,
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    FOREIGN KEY (office_id) REFERENCES offices(id),
    CONSTRAINT uk_doctors_phone UNIQUE (phone)
);

CREATE TABLE IF NOT EXISTS patient_cards (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    symptoms VARCHAR(255) NOT NULL,
    diagnosis VARCHAR(255) NOT NULL,
    meds VARCHAR(255),
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE IF NOT EXISTS patients (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(30) NOT NULL,
    birth_date DATE NOT NULL,
    phone VARCHAR(20) NOT NULL,
    patient_card_id BIGINT NOT NULL,
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    insurance_id BIGINT NOT NULL,
    FOREIGN KEY (patient_card_id) REFERENCES patient_cards(id),
    CONSTRAINT uk_patients_phone UNIQUE (phone)
);

CREATE TABLE IF NOT EXISTS appointments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    date TIMESTAMP NOT NULL,
    doctor_id BIGINT NOT NULL,
    patient_id BIGINT NOT NULL,
    work_hours_from TIMESTAMP NOT NULL,
    work_hours_for TIMESTAMP NOT NULL,
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    card_id BIGINT NOT NULL,
    insurance_id BIGINT NOT NULL,
    office_id BIGINT NOT NULL,
    FOREIGN KEY (doctor_id) REFERENCES doctors(id),
    FOREIGN KEY (patient_id) REFERENCES patients(id),
    FOREIGN KEY (card_id) REFERENCES patient_cards(id),
    FOREIGN KEY (office_id) REFERENCES offices(id),
    CONSTRAINT chk_appointment_time CHECK (work_hours_for > work_hours_from)
);

CREATE TABLE IF NOT EXISTS users (
    username VARCHAR(30) PRIMARY KEY,
    password VARCHAR NOT NULL,
    roles VARCHAR(255) NOT NULL,
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE IF NOT EXISTS doctor_schedule (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    doctor_id BIGINT NOT NULL,
    day_of_week SMALLINT NOT NULL CHECK (day_of_week BETWEEN 1 AND 7),
    start_time TIME NOT NULL,
    end_time TIME NOT NULL,
    office_id BIGINT,
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    FOREIGN KEY (doctor_id) REFERENCES doctors(id),
    FOREIGN KEY (office_id) REFERENCES offices(id)
);

CREATE TABLE IF NOT EXISTS patient_cards_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    card_id BIGINT NOT NULL,
    changed_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    changed_by VARCHAR(50),
    old_diagnosis VARCHAR(255),
    new_diagnosis VARCHAR(255) NOT NULL,
    old_meds TEXT,
    new_meds TEXT,
    change_reason TEXT,
    FOREIGN KEY (card_id) REFERENCES patient_cards(id)
);

CREATE TABLE IF NOT EXISTS specializations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    description TEXT,
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE IF NOT EXISTS doctor_specializations (
    doctor_id BIGINT NOT NULL,
    specialization_id BIGINT NOT NULL,
    PRIMARY KEY (doctor_id, specialization_id),
    FOREIGN KEY (doctor_id) REFERENCES doctors(id),
    FOREIGN KEY (specialization_id) REFERENCES specializations(id)
);

CREATE INDEX IF NOT EXISTS idx_doctors_office ON doctors(office_id);
CREATE INDEX IF NOT EXISTS idx_patients_card ON patients(patient_card_id);
CREATE INDEX IF NOT EXISTS idx_appointments_doctor ON appointments(doctor_id);
CREATE INDEX IF NOT EXISTS idx_appointments_patient ON appointments(patient_id);
CREATE INDEX IF NOT EXISTS idx_doctor_schedule_doctor ON doctor_schedule(doctor_id);
CREATE INDEX IF NOT EXISTS idx_patient_history_card ON patient_cards_history(card_id);